services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goserver-mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - '${SERVER_PORT}:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      - mongo
      - redis
    networks:
      - goserve-mongo-network

  mongo:
    image: mongo:8.0.9
    restart: unless-stopped
    env_file: .env
    ports:
      - '${DB_PORT}:27017'
    command: mongod --bind_ip_all
    volumes:
      - ./.extra/setup/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db
    networks:
      - goserve-mongo-network

  redis:
    image: redis:8.4.0
    restart: unless-stopped
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --bind localhost --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data/cache
    networks:
      - goserve-mongo-network

networks:
  goserve-mongo-network:
    driver: bridge

volumes:
  dbdata:
  cache:
    driver: local